EduHomePractice/EduHomePractice/Models/About.cs
namespace EduHomePractice.Models
{
    public class About
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    }
}

EduHomePractice/EduHomePractice/Models/Course.cs
namespace EduHomePractice.Models
{
    public class Course
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    }
}

EduHomePractice/EduHomePractice/Models/ErrorViewModel.cs
using System;

namespace EduHomePractice.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EduHomePractice/EduHomePractice/Models/Service.cs
namespace EduHomePractice.Models
{
    public class Service
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

EduHomePractice/EduHomePractice/Models/Slider.cs
namespace EduHomePractice.Models
{
    public class Slider
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
    }
}

EduHomePractice/EduHomePractice/ViewModels/HomeVM.cs
using EduHomePractice.Models;
using System.Collections.Generic;

namespace EduHomePractice.ViewModels
{
    public class HomeVM
    {
        public List<Slider> Sliders { get; set; }
        public List<Service> Services { get; set; }
        public About About { get; set; }
    }
}

EduHomePractice/EduHomePractice/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;

namespace EduHomePractice.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EduHomePractice/EduHomePractice/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;

namespace EduHomePractice.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Register()
        {
            return View();
        }
    }
}

EduHomePractice/EduHomePractice/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;

namespace EduHomePractice.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EduHomePractice/EduHomePractice/Controllers/HomeController.cs
using EduHomePractice.DAL;
using EduHomePractice.Models;
using EduHomePractice.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EduHomePractice.Controllers
{
    public class HomeController : Controller
    {
        private readonly AppDbContext _db;
        public HomeController(AppDbContext db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            HomeVM homeVM = new HomeVM
            {
                Sliders = await _db.Sliders.ToListAsync(),
                Services =await _db.Services.OrderByDescending(x=>x.Id).Take(3).ToListAsync(),
                About = await _db.About.FirstOrDefaultAsync(),
            };

            return View(homeVM);
        }
        public IActionResult Error()
        {
            return View();
        }
    }
}

EduHomePractice/EduHomePractice/Controllers/TeachersController.cs
using Microsoft.AspNetCore.Mvc;

namespace EduHomePractice.Controllers
{
    public class TeachersController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EduHomePractice/EduHomePractice/ViewComponents/CoursesViewComponent.cs
using EduHomePractice.DAL;
using EduHomePractice.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EduHomePractice.ViewComponents
{
    public class CoursesViewComponent: ViewComponent
    {
        private readonly AppDbContext _db;
        public CoursesViewComponent(AppDbContext db)
        {
            _db = db;
        }
        public async Task<IViewComponentResult> InvokeAsync(int take)
        {
            List<Course> courses = new List<Course>();
            if (take==0)
            {
                courses = await _db.Courses.ToListAsync();
                return View(courses);
            }
            courses = await _db.Courses.Take(3).ToListAsync();
           
            return View(courses);
        }
    }
}

EduHomePractice/EduHomePractice/Views/About/Index.cshtml
<!-- Banner Area Start -->
<div class="banner-area-wrapper">
    <div class="banner-area text-center">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="banner-content-wrapper">
                        <div class="banner-content">
                            <h2>about us</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Banner Area End -->
<!-- About Start -->
<div class="about-area pt-145 pb-155">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <div class="about-content">
                    <h2>WELCOME TO <span>EDUHOME</span></h2>
                    <p>I must explain to you how all this mistaken idea of denouncing pleure and prsing pain was born and I will give you a complete account of the system, and expound the actual teachings  the master-builder of humanit happiness</p>
                    <p class="hidden-sm">I must explain to you how all this mistaken idea of denouncing pleure and prsing pain was born and I will give you a complete account of the system</p>
                    <a class="default-btn" href="#">view courses</a>
                </div>
            </div>
            <div class="col-md-6 col-sm-6">
                <div class="about-img">
                    <img src="~/img/about/about.png" alt="about">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- About End -->
<!-- Teacher Start -->
<div class="teacher-area pb-150">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="section-title text-center">
                    <img src="~/img/icon/section.png" alt="title">
                    <h2>meet our teachers</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-sm-4 col-xs-12">
                <div class="single-teacher">
                    <div class="single-teacher-img">
                        <a href="teacher-details.html"><img src="~/img/teacher/teacher1.jpg" alt="teacher"></a>
                    </div>
                    <div class="single-teacher-content text-center">
                        <h2><a href="teacher-details.html">STUART KELVIN</a></h2>
                        <h4>Associate Professor</h4>
                        <ul>
                            <li><a href="https://www.facebook.com/devitems/?ref=bookmarks"><i class="zmdi zmdi-facebook"></i></a></li>
                            <li><a href="https://www.pinterest.com/devitemsllc/"><i class="zmdi zmdi-pinterest"></i></a></li>
                            <li><a href="#"><i class="zmdi zmdi-vimeo"></i></a></li>
                            <li><a href="https://twitter.com/devitemsllc"><i class="zmdi zmdi-twitter"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-4 col-xs-12">
                <div class="single-teacher">
                    <div class="single-teacher-img">
                        <a href="teacher-details.html"><img src="~/img/teacher/teacher2.jpg" alt="teacher"></a>
                    </div>
                    <div class="single-teacher-content text-center">
                        <h2><a href="teacher-details.html">eamily cristian</a></h2>
                        <h4>Associate Professor</h4>
                        <ul>
                            <li><a href="https://www.facebook.com/devitems/?ref=bookmarks"><i class="zmdi zmdi-facebook"></i></a></li>
                            <li><a href="https://www.pinterest.com/devitemsllc/"><i class="zmdi zmdi-pinterest"></i></a></li>
                            <li><a href="#"><i class="zmdi zmdi-vimeo"></i></a></li>
                            <li><a href="https://twitter.com/devitemsllc"><i class="zmdi zmdi-twitter"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-3 col-sm-4 col-xs-12">
                <div class="single-teacher">
                    <div class="single-teacher-img">
                        <a href="teacher-details.html"><img src="~/img/teacher/teacher3.jpg" alt="teacher"></a>
                    </div>
                    <div class="single-teacher-content text-center">
                        <h2><a href="teacher-details.html">kevin williams</a></h2>
                        <h4>Associate Professor</h4>
                        <ul>
                            <li><a href="https://www.facebook.com/devitems/?ref=bookmarks"><i class="zmdi zmdi-facebook"></i></a></li>
                            <li><a href="https://www.pinterest.com/devitemsllc/"><i class="zmdi zmdi-pinterest"></i></a></li>
                            <li><a href="#"><i class="zmdi zmdi-vimeo"></i></a></li>
                            <li><a href="https://twitter.com/devitemsllc"><i class="zmdi zmdi-twitter"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-md-3 hidden-sm col-xs-12">
                <div class="single-teacher">
                    <div class="single-teacher-img">
                        <a href="teacher-details.html"><img src="~/img/teacher/teacher4.jpg" alt="teacher"></a>
                    </div>
                    <div class="single-teacher-content text-center">
                        <h2><a href="teacher-details.html">salina gomaze</a></h2>
                        <h4>Associate Professor</h4>
                        <ul>
                            <li><a href="https://www.facebook.com/devitems/?ref=bookmarks"><i class="zmdi zmdi-facebook"></i></a></li>
                            <li><a href="https://www.pinterest.com/devitemsllc/"><i class="zmdi zmdi-pinterest"></i></a></li>
                            <li><a href="#"><i class="zmdi zmdi-vimeo"></i></a></li>
                            <li><a href="https://twitter.com/devitemsllc"><i class="zmdi zmdi-twitter"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Teacher End -->
<!-- Testimonial Area Start -->
<div class="testimonial-area pt-110 pb-105 text-center">
    <div class="container">
        <div class="row">
            <div class="testimonial-owl owl-theme owl-carousel">
                <div class="col-md-8 col-md-offset-2 col-sm-12">
                    <div class="single-testimonial">
                        <div class="testimonial-info">
                            <div class="testimonial-img">
                                <img src="~/img/testimonial/testimonial.jpg" alt="testimonial">
                            </div>
                            <div class="testimonial-content">
                                <p>I must explain to you how all this mistaken idea of denoung pleure and praising pain was born and I will give you a coete account of the system, and expound the actual</p>
                                <h4>David Morgan</h4>
                                <h5>Student, CSE</h5>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Testimonial Area End -->
<!-- Notice Start -->
<section class="notice-area two pt-140 pb-100">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="notice-right-wrapper mb-25 pb-25">
                    <h3>TAKE A VIDEO TOUR</h3>
                    <div class="notice-video">
                        <div class="video-icon video-hover">
                            <a class="video-popup" href="https://www.youtube.com/watch?v=to6Ghf8UL7o">
                                <i class="zmdi zmdi-play"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="notice-left-wrapper">
                    <h3>notice board</h3>
                    <div class="notice-left">
                        <div class="single-notice-left mb-23 pb-20">
                            <h4>5, June 2017</h4>
                            <p>I must explain to you how all this mistaken idea of denouncing plasure and praising pain was born and I will give you a complete </p>
                        </div>
                        <div class="single-notice-left hidden-sm mb-23 pb-20">
                            <h4>4, June 2017</h4>
                            <p>I must explain to you how all this mistaken idea of denouncing plasure and praising pain was born and I will give you a complete </p>
                        </div>
                        <div class="single-notice-left pb-70">
                            <h4>3, June 2017</h4>
                            <p>I must explain to you how all this mistaken idea of denouncing plasure and praising pain was born and I will give you a complete </p>
                        </div>
                        <div class="single-notice-left mb-23 pb-20">
                            <h4>5, June 2017</h4>
                            <p>I must explain to you how all this mistaken idea of denouncing plasure and praising pain was born and I will give you a complete </p>
                        </div>
                        <div class="single-notice-left hidden-sm mb-23 pb-20">
                            <h4>4, June 2017</h4>
                            <p>I must explain to you how all this mistaken idea of denouncing plasure and praising pain was born and I will give you a complete </p>
                        </div>
                        <div class="single-notice-left pb-70">
                            <h4>3, June 2017</h4>
                            <p>I must explain to you how all this mistaken idea of denouncing plasure and praising pain was born and I will give you a complete </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Notice End -->

EduHomePractice/EduHomePractice/Views/Courses/Index.cshtml
<!-- Banner Area Start -->
<div class="banner-area-wrapper">
    <div class="banner-area text-center">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="banner-content-wrapper">
                        <div class="banner-content">
                            <h2>courses</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Banner Area End -->
<!-- Course Start -->
<div class="course-area pt-150 pb-150">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="course-title">
                    <h3>search courses</h3>
                </div>
                <div class="course-form">
                    <form id="search" action="#">
                        <input type="search" placeholder="Search..." name="search" />
                        <button type="submit">search</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="row">
            @await Component.InvokeAsync("Courses", new{take=0})
                       
        </div>
    </div>
</div>
<!-- Course End -->

EduHomePractice/EduHomePractice/Views/Shared/Components/Courses/Default.cshtml
@model List<Course>
@foreach (Course courses in Model)
{
    <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="single-course mb-70">
            <div class="course-img">
                <a asp-controller="Courses" asp-action="Index">
                    <img src="~/img/course/@courses.Image" alt="course">
                    <div class="course-hover">
                        <i class="fa fa-link"></i>
                    </div>
                </a>
            </div>
            <div class="course-content">
                <h3><a asp-controller="Courses" asp-action="Index">@courses.Name</a></h3>
                <p>@courses.Description</p>
                <a class="default-btn" asp-controller="Courses" asp-action="Index">read more</a>
            </div>
        </div>
    </div>
}

EduHomePractice/EduHomePractice/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="en">

<!-- Mirrored from demo.devitems.com/eduhome/index-2.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 21 Jun 2020 19:37:50 GMT -->
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Eduhome - Educational HTML Template</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <!-- Place favicon.ico in the root directory -->

    <link rel="stylesheet" href="~/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/css/animate.css">
    <link rel="stylesheet" href="~/css/meanmenu.css">
    <link rel="stylesheet" href="~/css/magnific-popup.css">
    <link rel="stylesheet" href="~/css/owl.carousel.min.css">
    <link rel="stylesheet" href="~/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/et-line-icon.css">
    <link rel="stylesheet" href="~/css/reset.css">
    <link rel="stylesheet" href="~/css/ionicons.min.css">
    <link rel="stylesheet" href="~/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/responsive.css">
    <script src="~/js/vendor/modernizr-2.8.3.min.js"></script>
</head>
<body>
    <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
    <!-- Header Area Start -->
    <header class="top">
        <div class="header-top">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-sm-8 col-xs-12">
                        <div class="header-top-left">
                            <p>HAVE ANY QUESTION ?  +880 5698  598  6587</p>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4 col-xs-12">
                        <div class="header-top-right text-right">
                            <ul>
                                <li><a asp-controller="Account" asp-action="Login">login</a></li>
                                <li><a asp-controller="Account" asp-action="Register">signup</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="header-area two header-sticky">
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-3 col-xs-6">
                        <div class="logo">
                            <a asp-controller="Home" asp-action="Index"><img src="~/img/logo/logo2.png" alt="eduhome" /></a>
                        </div>
                    </div>
                    <div class="col-md-9 col-sm-9 col-xs-6">
                        <div class="content-wrapper text-right">
                            <!-- Main Menu Start -->
                            <div class="main-menu">
                                <nav>
                                    <ul>
                                        <li>
                                            <a asp-controller="Home" asp-action="Index">Home</a>
                                        </li>
                                        <li><a asp-controller="About" asp-action="Index">About</a></li>
                                        <li>
                                            <a asp-controller="Courses" asp-action="Index">courses</a>
                                        </li>
                                        <li>
                                            <a asp-controller="Events" asp-action="Index">events</a>
                                        </li>
                                        <li class="hidden-sm">
                                            <a asp-controller="Teachers" asp-action="Index">teachers</a>
                                        </li>
                                        <li>
                                            <a asp-controller="Blogs" asp-action="Index">blogs</a>
                                        </li>
                                        <li><a asp-controller="Contact" asp-action="Index">Contact</a></li>
                                    </ul>
                                </nav>
                            </div>
                            <!--Search Form Start-->
                            <div class="search-btn">
                                <ul data-toggle="dropdown" class="header-search search-toggle">
                                    <li class="search-menu">
                                        <i class="fa fa-search"></i>
                                    </li>
                                </ul>
                                <div class="search">
                                    <div class="search-form">
                                        <form id="search-form" action="#">
                                            <input type="search" placeholder="Search here..." name="search" />
                                            <button type="submit">
                                                <span><i class="fa fa-search"></i></span>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                            <!--End of Search Form-->
                            <!-- Main Menu End -->
                        </div>
                    </div>
                    <div class="col-xs-12">
                        <div class="mobile-menu hidden-lg hidden-md hidden-sm"></div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Header Area End -->
            @RenderBody()
    <!-- Subscribe Start -->
    <div class="subscribe-area pt-60 pb-70">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <div class="subscribe-content section-title text-center">
                        <h2>subscribe our newsletter</h2>
                        <p>I must explain to you how all this mistaken idea </p>
                    </div>
                    <div class="newsletter-form mc_embed_signup">
                        <form action="http://devitems.us11.list-manage.com/subscribe/post?u=6bbb9b6f5827bd842d9640c82&amp;id=05d85f18ef" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                            <div id="mc_embed_signup_scroll" class="mc-form">
                                <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="Enter your e-mail address" required>
                                <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                                <div class="mc-news" aria-hidden="true"><input type="text" name="b_6bbb9b6f5827bd842d9640c82_05d85f18ef" tabindex="-1" value=""></div>
                                <button id="mc-embedded-subscribe" class="default-btn" type="submit" name="subscribe"><span>subscribe</span></button>
                            </div>
                        </form>
                        <!-- mailchimp-alerts Start -->
                        <div class="mailchimp-alerts">
                            <div class="mailchimp-submitting"></div><!-- mailchimp-submitting end -->
                            <div class="mailchimp-success"></div><!-- mailchimp-success end -->
                            <div class="mailchimp-error"></div><!-- mailchimp-error end -->
                        </div>
                        <!-- mailchimp-alerts end -->
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Subscribe End -->
    <!-- Footer Start -->
    <footer class="footer-area">
        <div class="main-footer">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-6 col-xs-12">
                        <div class="single-widget pr-60">
                            <div class="footer-logo pb-25">
                                <a asp-controller="Home" asp-action="Index"><img src="~/img/logo/footer-logo.png" alt="eduhome"></a>
                            </div>
                            <p>I must explain to you how all this mistaken idea of denoung pleure and praising pain was born and give you a coete account of the system. </p>
                            <div class="footer-social">
                                <ul>
                                    <li><a href="#"><i class="zmdi zmdi-facebook"></i></a></li>
                                    <li><a href="#"><i class="zmdi zmdi-pinterest"></i></a></li>
                                    <li><a href="#"><i class="zmdi zmdi-vimeo"></i></a></li>
                                    <li><a href="#"><i class="zmdi zmdi-twitter"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <div class="single-widget">
                            <h3>information</h3>
                            <ul>
                                <li><a href="#">addmission</a></li>
                                <li><a href="#">Academic Calender</a></li>
                                <li><a href="event.html">Event List</a></li>
                                <li><a href="#">Hostel &amp; Dinning</a></li>
                                <li><a href="#">TimeTable</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-2 col-sm-6 col-xs-12">
                        <div class="single-widget">
                            <h3>useful links</h3>
                            <ul>
                                <li><a href="course.html">our courses</a></li>
                                <li><a href="about.html">about us</a></li>
                                <li><a href="teacher.html">teachers &amp; faculty</a></li>
                                <li><a href="#">teams &amp; conditions</a></li>
                                <li><a href="event.html">our events</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-6 col-xs-12">
                        <div class="single-widget">
                            <h3>get in touch</h3>
                            <p>Your address goes here, Street<br>City, Roadno 785 New York</p>
                            <p>+880  548  986  898  87<br>+880  659  785  658  98</p>
                            <p>info@eduhome.com<br>www.eduhome.com</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom text-center">
            <div class="container">
                <div class="row">
                    <div class="col-xs-12">
                        <p>Copyright © <a href="#" target="_blank">HasTech</a> 2017. All Right Reserved By Hastech.</p>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Footer End -->

    <script src="~/js/vendor/jquery-1.12.0.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/jquery.meanmenu.js"></script>
    <script src="~/js/jquery.magnific-popup.js"></script>
    <script src="~/js/ajax-mail.js"></script>
    <script src="~/js/owl.carousel.min.js"></script>
    <script src="~/js/jquery.mb.YTPlayer.js"></script>
    <script src="~/js/jquery.nicescroll.min.js"></script>
    <script src="~/js/plugins.js"></script>
    @RenderSection("Scripts", false)
    <script src="~/js/main.js"></script>
</body>

<!-- Mirrored from demo.devitems.com/eduhome/index-2.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 21 Jun 2020 19:41:25 GMT -->
</html>